### ISSUE TITLE
Add pre-commit and pre-push git hooks

### ISSUE THREAD

**Issue by psealock** [woocommerce/navigation#11]
wc-admin has pre push and commit hooks. This project should have those too.

- [x] Run tests before pushing
- [x] Run linter and prettier before commits

**Comment by mattsherman** [comment]
I'll grab this one -- I've wanted to learn more about GH hooks and Travis.

**Comment by mattsherman** [comment]
Unassigning myself for now, while I take care of #14 first.

**Comment by mattsherman** [comment]
Split Travis integration out into #25
