### ISSUE TITLE
Add menu, title, and button styling

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/navigation#65]
Once https://github.com/woocommerce/navigation/pull/63 is merged we can begin styling the component to match the designs.

There are some old scss styles that may need to be removed or selectors modified.  This also may be a good opportunity to switch to a css-in-js solution since we did the same with the GB component.  Any opinion on this @psealock?

<img width="169" alt="Screen Shot 2020-08-27 at 5 55 46 PM" src="https://user-images.githubusercontent.com/10561050/91498879-3a281f80-e8c9-11ea-8391-bbfdfe4c775e.png">

**Comment by psealock** [comment]
With https://github.com/WordPress/gutenberg/pull/24107 merged, these styles are handled upstream
