### ISSUE TITLE
Set active item ID for navigation

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/navigation#66]
We need to be able to determine the active ID.  Some considerations on how this might be determined:

* By default, check if the current URL matches the menu item.
* Allow a third party plugin to determine active state if necessary.
* We may need to determine the active state server-side and hydrate this data to avoid delays in determining the active state.

**Comment by psealock** [comment]
See https://github.com/WordPress/gutenberg/pull/25281 for progress. I'm thinking it will look something like this:

```js
import { Link } from '@woocommerce/components';
import { getNewPath } from '@woocommerce/navigation';

...
<NavigationItem>
	<Link
		href={ getNewPath( '/analytics/products', {
			filter: 'single_product',
			products: product.id,
		} ) }
		type="wc-admin"
	>
		{ product.name }
	</Link>
</NavigationItem>
```
