### ISSUE TITLE
Get warning on Coupon page

### ISSUE THREAD

**Issue by kishanjasani** [woocommerce/navigation#71]
Reproduce issue steps: 
Install the latest WordPress version
Theme: Twenty Twenty 

- Now Click on `Woo-Commerce`.
- Inside that Click on `Coupons`.
- Now Check the console of your browser.

You will get 2 Warnings: 
- `Warning: Invalid DOM property fill-rule. Did you mean fillRule?`
- `Warning: Invalid DOM property clip-rule. Did you mean clipRule?`

**Comment by joshuatf** [comment]
Hi @kishanjasani - thanks for noting that issue.  This repository is for the new WooCommerce navigation experience.  I think the issue you mentioned may be stemming from the new marketing pages in WooCommerce Admin, so I'll move this issue over there.

**Comment by joshuatf** [comment]
Issue moved to [woocommerce/woocommerce-admin #5066](https://github.com/woocommerce/woocommerce-admin/issues/5066) via [**ZenHub**](https://www.zenhub.com/)
